application: topsnight13
version: a2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: honey.app
  
libraries:
- name: jinja2
  version: latest
  
builtins:
- remote_api: on
